linux-test:
  script:
    - echo $USER
    - docker build -f Dockerfile.linux -t aspose-words-cloud-cpp:linux .
    - docker run --rm -v "$PWD:/aspose-words-cloud-cpp/" aspose-words-cloud-cpp:linux bash aspose-words-cloud-cpp/scripts/runAll.sh $WordsAppKey $WordsAppSid $WordsBaseUrl
  tags:
    - awcloud-linux
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml