linux-test:
  script:
    - cmd /c 'docker build --platform linux -f Dockerfile.linux -t aspose-words-cloud-cpp:linux .'
    - cmd /c 'runInDocker.linux.bat %WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
  tags:
    - awcloud
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml