variables:
  GIT_STRATEGY: clone

windows-test:
  script:
    - cmd /c 'docker build -f Dockerfile.windows -t aspose-words-cloud-cpp:windows .'
    - cmd /c 'runInDocker.windows.bat 1%WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
    - Get-ChildItem -Path . -Recurse
  tags:
    - awcloud
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/3test_result.xml