variables:
  GIT_STRATEGY: clone

windows-test:
  script:
    - Write-Host $env:GIT_CI_USER $env:GIT_CI_PASS
    - docker build -f Dockerfile.windows -t aspose-words-cloud-cpp:windows .
    - cmd /c 'runInDocker.windows.bat %WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
  tags:
    - awcloud
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml