linux-test:
  script:
    - cmd /c 'runInDocker.linux.bat %WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
  tags:
    - awcloud
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml