variables:
  GIT_STRATEGY: clone

windows-test:
  script:
    - docker build -f Dockerfile.windows -t aspose-words-cloud-cpp:windows .
    - cmd /c 'runInDocker.windows.bat 1%WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
    - ?$
  tags:
    - awcloud
  artifacts:
    expire_in: 1 hour
    reports:
      junit: ./out/test_result.xml