variables:
  GIT_STRATEGY: clone

windows-test:
  script:
    - docker build -f Dockerfile.windows -t aspose-words-cloud-cpp:windows .
    - cmd /c 'runInDocker.windows.bat 1%WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
    - Write-Host %GIT_CI_USER% %GIT_CI_PASS%
  tags:
    - awcloud
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml