stages:
  - stage1
  - stage2
  - stage3
  
stage1:
  stage: stage1
  script:
    - Write-Host stage1
  tags:
    - awcloud

stage2:
  stage: stage2
  script:
    - Write-Host stage2
  tags:
    - awcloud
  when: manual
  
stage3.1:
  stage: stage3
  script:
    - Write-Host stage3.1
  tags:
    - awcloud

stage3.2:
  stage: stage3
  script:
    - Write-Host stage3.2
  tags:
    - awcloud