start:
  script:
    - Write-Host start
    - git branch -v
    - git push origin HEAD:test-junit1 
  tags:
    - awcloud
  only:
    - test-junit

finish:
  script:
    - Write-Host finish
    - git branch -v
  tags:
    - awcloud
  only:
    - test-junit1