stages:
  - start
  - finish

start:
  script:
    - $env:origin += 'https://{0}:{1}@git.auckland.dynabic.com/words-cloud/words-cloud-cpp.git' -f $env:GIT_CI_USER, $env:GIT_CI_PASS
    - "git push $env:origin HEAD:test-junit1"
  tags:
    - awcloud
  only:
    - test-junit
  stage: start

finish:
  script:
    - Write-Host finish
    - git branch -v
  tags:
    - awcloud
  only:
    - test-junit1
  stage: finish