variables:
  GIT_STRATEGY: clone

before_script:
  - $Env:SDK_VERSION += ((Get-Date).AddMonths(1)).tostring("yy.M")  
  
windows-test:
  script:
    - Write-Host $env:SDK_VERSION
  tags:
    - awcloud